### ISSUE TITLE
Having trouble using html with vectors nested inside a vector

### ISSUE THREAD

**Issue by mabasic** [phel-lang/phel-lang#287]
To recreate, in the REPL:

```
(require phel\html :refer [html])

(html [[:script {:src "test"}]])
```

returns:

```
Error in expanding macro "phel\html\html": [:script {:src "test"}] is not a valid element name.
in string:2

2| (html [[:script {:src "test"}]])
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Caused by:
#0 /tmp/__phelZtt15h(8): Phel\Lang\AbstractFn@anonymous->__invoke()
#1 /tmp/__pheliwn1ll(11): Phel\Lang\AbstractFn@anonymous->__invoke()
#2 /tmp/__phelhqftsm(9): Phel\Lang\AbstractFn@anonymous->__invoke()
#3 /tmp/__phelPOXCHk(9): Phel\Lang\AbstractFn@anonymous->__invoke()
#4 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Compiler/Analyzer/TypeAnalyzer/SpecialForm/InvokeSymbol.php(59): Phel\Lang\AbstractFn@anonymous->__invoke()
#5 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Compiler/Analyzer/TypeAnalyzer/SpecialForm/InvokeSymbol.php(43): Phel\Compiler\Analyzer\TypeAnalyzer\SpecialForm\InvokeSymbol->macroExpand()
#6 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Compiler/Analyzer/TypeAnalyzer/SpecialForm/InvokeSymbol.php(30): Phel\Compiler\Analyzer\TypeAnalyzer\SpecialForm\InvokeSymbol->globalMacro()
#7 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Compiler/Analyzer/TypeAnalyzer/AnalyzePersistentList.php(53): Phel\Compiler\Analyzer\TypeAnalyzer\SpecialForm\InvokeSymbol->analyze()
#8 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Compiler/Analyzer/Analyzer.php(114): Phel\Compiler\Analyzer\TypeAnalyzer\AnalyzePersistentList->analyze()
#9 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Compiler/Compiler/EvalCompiler.php(94): Phel\Compiler\Analyzer\Analyzer->analyze()
#10 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Compiler/Compiler/EvalCompiler.php(74): Phel\Compiler\Compiler\EvalCompiler->evalNode()
#11 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Compiler/CompilerFacade.php(36): Phel\Compiler\Compiler\EvalCompiler->eval()
#12 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Command/Repl/ReplCommand.php(133): Phel\Compiler\CompilerFacade->eval()
#13 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Command/Repl/ReplCommand.php(71): Phel\Command\Repl\ReplCommand->analyzeInputBuffer()
#14 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Command/Repl/ReplCommand.php(62): Phel\Command\Repl\ReplCommand->loopReadLineAndAnalyze()
#15 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Command/CommandFacade.php(21): Phel\Command\Repl\ReplCommand->run()
#16 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/PhelFacade.php(77): Phel\Command\CommandFacade->executeReplCommand()
#17 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/PhelFacade.php(54): Phel\PhelFacade->executeReplCommand()
#18 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/phel(23): Phel\PhelFacade->runCommand()
#19 {main}
```

When used with the old array data structure it works:

```
(html @[[:script {:src "test"}]])

<script src="test"></script>
```

**Comment by mabasic** [comment]
As a workaround I've managed to get it working with lists, like so:

```
(html (list [:script {:src "test"}]))
```

**Comment by mabasic** [comment]
This affects `for` loops mentioned in  #275 

The for loop now correctly returns a vector instead of an array, but using a vector like shown above with `html` produces an error.

Can I convert a vector to a list to avoid this ftm?

**Comment by jenshaase** [comment]
Hi, 

it is correct that this is not working. What you can do is to wrap it in a outer element:
```
(html [:div [:span "a"] [:span "b"]])
```

or use multiple arguments:
```
(html [:span "a"] [:span "b"])
```

As alternative you can convert it to a list or to a PHP array (PHP array should be faster):
```
(html (apply php/array [[:span "a"] [:span "b"]]))
(html (apply list [[:span "a"] [:span "b"]]))
(html (apply php/array (for ...)))
```

**Comment by mabasic** [comment]
I see. Thank you for the solutions. I got it working with:

```
(html (apply php/array (for ...)))
```

I could probably try to tackle this, but I don't know when. I'm trying to finish my website so that I can move to other projects xD.

**Comment by mabasic** [comment]
Shouldn't this be kept open since it worked before with arrays?

This is a very common thing to do

**Comment by jenshaase** [comment]
Sorry, I forget to add a comment here. With the current design it is not possible to archive this. I can't make a decision if the first vector is meant to be a list of elements or a element.

**Comment by mabasic** [comment]
Aha, I see. Should I then add the code samples from above in the documentation for HTML?

**Comment by mabasic** [comment]
Just going to leave this here for future reference:

```
(defn convert-to-php-array
  "This should be faster than converting to a list instead"
  [vector]
  (apply php/array vector))
```

another way (preferred):

```
(list vector)
```
