### ISSUE TITLE
CompiledCodeIsMalformedException: Too few arguments to function Phel\Lang\Collections\Vector\AbstractPersistentVector::__invoke()

### ISSUE THREAD

**Issue by mabasic** [phel-lang/phel-lang#288]
This is strange.

Place this inside a file and require it in the REPL:

```
(ns app\pages\portfolio)

(def white
  [:div
   [:h1 {:class "display-1 pt-5 mt-5"} "Portfolio"]
   [:p [:a {:href "/" :class "text-dark"} "home"] "/ portfolio"]])
```

```
vendor/bin/phel repl
(require app\pages\portfolio)
(portfolio/white)
```

You will get an error similar to this one:

```
Phel\Compiler\Evaluator\Exceptions\CompiledCodeIsMalformedException: Too few arguments to function Phel\Lang\Collections\Vector\AbstractPersistentVector::__invoke(), 0 passed in /tmp/__phelpF6aZq on line 4 and exactly 1 expected
in /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Compiler/Evaluator/Exceptions/CompiledCodeIsMalformedException.php:14 (gen: /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Compiler/Evaluator/Exceptions/CompiledCodeIsMalformedException.php:14)

#0 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Compiler/Evaluator/RequireEvaluator.php(36): Phel\Compiler\Evaluator\Exceptions\CompiledCodeIsMalformedException::fromThrowable()
#1 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Compiler/Compiler/EvalCompiler.php(99): Phel\Compiler\Evaluator\RequireEvaluator->eval()
#2 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Compiler/Compiler/EvalCompiler.php(74): Phel\Compiler\Compiler\EvalCompiler->evalNode()
#3 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Compiler/CompilerFacade.php(36): Phel\Compiler\Compiler\EvalCompiler->eval()
#4 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Command/Repl/ReplCommand.php(133): Phel\Compiler\CompilerFacade->eval()
#5 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Command/Repl/ReplCommand.php(71): Phel\Command\Repl\ReplCommand->analyzeInputBuffer()
#6 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Command/Repl/ReplCommand.php(62): Phel\Command\Repl\ReplCommand->loopReadLineAndAnalyze()
#7 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/Command/CommandFacade.php(21): Phel\Command\Repl\ReplCommand->run()
#8 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/PhelFacade.php(77): Phel\Command\CommandFacade->executeReplCommand()
#9 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/src/php/PhelFacade.php(54): Phel\PhelFacade->executeReplCommand()
#10 /home/mabasic/code/src/github.com/mabasic/mariobasic-n7/vendor/phel-lang/phel-lang/phel(23): Phel\PhelFacade->runCommand()
```
but if you change the `white` variable to become a function it all works:

```
(ns app\pages\portfolio)

(defn white []
  [:div
   [:h1 {:class "display-1 pt-5 mt-5"} "Portfolio"]
   [:p [:a {:href "/" :class "text-dark"} "home"] "/ portfolio"]])
```

Any ideas?

**Comment by jenshaase** [comment]
You put `(portfolio/white)` in parentheses. This tries to execute `white` and since it is a vector it will call `__invoke` on a vector. That method expects one parameter. So you should remove the parentheses.

**Comment by mabasic** [comment]
Does that mean that I can't have a vector in a variable? How would I reference it in code then?

**Comment by mabasic** [comment]
Oh man, this breaks a bunch of stuff for me xD

**Comment by jenshaase** [comment]
You can still use it. It is just a variable. In the repl you can type `portofolio/white` instead of `(portfolio/white)` and it prints the vector.

**Comment by mabasic** [comment]
My issue is that I was reliant on being able to use parentheses for variables and functions, so that I can accept both functions and variables. I'll just change the code to be functions
