### ISSUE TITLE
Could not find config key "export" in "Gacela\Framework\Config"

### ISSUE THREAD

**Issue by mabasic** [phel-lang/phel-lang#369]
I have started updating my libraries and applications to Phel 4.0 and this is the first issue that I have come upon.

```
PHP Fatal error:  Uncaught Gacela\Framework\Exception\ConfigException: Could not find config key "export" in "Gacela\Framework\Config" in /home/mabasic/code/src/github.com/mabasic/phel-json/vendor/gacela-project/gacela/src/Framework/Exception/ConfigException.php:21
Stack trace:
#0 /home/mabasic/code/src/github.com/mabasic/phel-json/vendor/gacela-project/gacela/src/Framework/Config.php(82): Gacela\Framework\Exception\ConfigException::keyNotFound()
#1 /home/mabasic/code/src/github.com/mabasic/phel-json/vendor/gacela-project/gacela/src/Framework/AbstractConfig.php(22): Gacela\Framework\Config->get()
#2 /home/mabasic/code/src/github.com/mabasic/phel-json/vendor/phel-lang/phel-lang/src/php/Interop/InteropConfig.php(25): Gacela\Framework\AbstractConfig->get()
#3 /home/mabasic/code/src/github.com/mabasic/phel-json/vendor/phel-lang/phel-lang/src/php/Interop/InteropFactory.php(43): Phel\Interop\InteropConfig->getExportTargetDirectory()
#4 /home/mabasic/code/src/github.com/mabasic/phel-json/vendor/phel-lang/phel-lang/src/php/Interop/InteropFactory.php(32): Phel\Interop\InteropFactory->createDirectoryRemover()
#5 /home/mabasic/code/src/github.com/mabasic/phel-json/vendor/phel-lang/phel-lang/src/php/Interop/InteropFacade.php(17): Phel\Interop\InteropFactory->createExportCommand()
#6 /home/mabasic/code/src/github.com/mabasic/phel-json/vendor/phel-lang/phel-lang/phel(34): Phel\Interop\InteropFacade->getExportCommand()
#7 {main}
  thrown in /home/mabasic/code/src/github.com/mabasic/phel-json/vendor/gacela-project/gacela/src/Framework/Exception/ConfigException.php on line 21
```

Nowhere in the documentation says that `export` field is required.

**Comment by mabasic** [comment]
I have managed to solve this by adding:

```
'export' => []
```

to the `phel-config.php` file.

But then I am seeing this warning:

```
PHP Warning:  Undefined array key "namespace-prefix" in /home/mabasic/code/src/github.com/mabasic/phel-json/vendor/phel-lang/phel-lang/src/php/Interop/InteropConfig.php on line 20
```

Maybe the gacela framework needs to have default values and ignore export key if none is provided.

**Comment by Chemaclass** [comment]
Yeah, that's a good point. I thought that the default values were already in place, but apparently, they are not.
For now, you could add the default values in your config file (to unblock you) but I will work on that. Thanks for reporting this!
