### ISSUE TITLE
Failed to run a REPL

### ISSUE THREAD

**Issue by mfaridw** [phel-lang/phel-lang#467]
| Q                   | A               |
|---------------------|-----------------|
| Phel version        | 0.6           |
| PHP version         | 8.1.2           |

#### Summary

I failed to run REPL from PowerShell. I have also tried to create a new project from the two methods provided but the result is still the same.

#### Current behavior

reproduce error messages :
```
stripos(): Argument #1 ($haystack) must be of type string, null given
#0 D:\farid\phel\hello-world\vendor\phel-lang\phel-lang\src\php\Run\Domain\Repl\ReplCommandSystemIo.php(71): stripos(NULL, 'editline')     
#1 D:\farid\phel\hello-world\vendor\phel-lang\phel-lang\src\php\Run\Command\ReplCommand.php(127): Phel\Run\Domain\Repl\ReplCommandSystemIo->isBracketedPasteSupported()
#2 D:\farid\phel\hello-world\vendor\phel-lang\phel-lang\src\php\Run\Command\ReplCommand.php(110): Phel\Run\Command\ReplCommand->addLineFromPromptToBuffer()
#3 D:\farid\phel\hello-world\vendor\phel-lang\phel-lang\src\php\Run\Command\ReplCommand.php(101): Phel\Run\Command\ReplCommand->loopReadLineAndAnalyze()
#4 D:\farid\phel\hello-world\vendor\symfony\console\Command\Command.php(298): Phel\Run\Command\ReplCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 D:\farid\phel\hello-world\vendor\symfony\console\Application.php(1015): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 D:\farid\phel\hello-world\vendor\symfony\console\Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Phel\Run\Command\ReplCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))        
#7 D:\farid\phel\hello-world\vendor\symfony\console\Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 D:\farid\phel\hello-world\vendor\phel-lang\phel-lang\phel(42): Symfony\Component\Console\Application->run()
#9 D:\farid\phel\hello-world\vendor\bin\phel(117): include('D:\\farid\\phel\\h...')
#10 {main}
```

#### How to reproduce

Run this command on powershell :
```.\vendor\bin\phel repl```

#### Expected behavior

successfully run REPL

**Comment by Chemaclass** [comment]
Fixed: https://github.com/phel-lang/phel-lang/pull/468
