### ISSUE TITLE
Compatibility of lists and vectors in the `cons` function

### ISSUE THREAD

**Issue by smeghead** [phel-lang/phel-lang#709]
| Q                   | A               |
|---------------------|-----------------|
| Phel version        | 0.14.1           |
| PHP version         | 8.2.19           |

#### Summary

The `cons` function works if the second argument is a list, but causes an error if it is a vector.

#### Current behavior

If you pass a vector as the second argument to the `cons` function, an error will occur.

```
phel:1> (cons 1 '(2 3))
(1 2 3)
phel:2> (cons 1 [2 3])
Phel\Compiler\Domain\Evaluator\Exceptions\CompiledCodeIsMalformedException: cannot do cons 1
in /usr/src/vendor/phel-lang/phel-lang/src/php/Compiler/Domain/Evaluator/Exceptions/CompiledCodeIsMalformedException.php:14 (gen: /usr/src/vendor/phel-lang/phel-lang/src/php/Compiler/Domain/Evaluator/Exceptions/CompiledCodeIsMalformedException.php:14)

#0 /usr/src/vendor/phel-lang/phel-lang/src/php/Compiler/Domain/Evaluator/RequireEvaluator.php(42): Phel\Compiler\Domain\Evaluator\Exceptions\CompiledCodeIsMalformedException::fromThrowable(Object(InvalidArgumentException))
#1 /usr/src/vendor/phel-lang/phel-lang/src/php/Compiler/Domain/Compiler/EvalCompiler.php(110): Phel\Compiler\Domain\Evaluator\RequireEvaluator->eval('// string
// ;;...')
#2 /usr/src/vendor/phel-lang/phel-lang/src/php/Compiler/Domain/Compiler/EvalCompiler.php(69): Phel\Compiler\Domain\Compiler\EvalCompiler->evalNode(Object(Phel\Compiler\Domain\Analyzer\Ast\CallNode), Object(Phel\Compiler\Infrastructure\CompileOptions))
#3 /usr/src/vendor/phel-lang/phel-lang/src/php/Compiler/CompilerFacade.php(57): Phel\Compiler\Domain\Compiler\EvalCompiler->evalString('(cons 1 [2 3])', Object(Phel\Compiler\Infrastructure\CompileOptions))
#4 /usr/src/vendor/phel-lang/phel-lang/src/php/Run/RunFacade.php(79): Phel\Compiler\CompilerFacade->eval('(cons 1 [2 3])', Object(Phel\Compiler\Infrastructure\CompileOptions))
#5 /usr/src/vendor/phel-lang/phel-lang/src/php/Run/Infrastructure/Command/ReplCommand.php(207): Phel\Run\RunFacade->eval('(cons 1 [2 3])', Object(Phel\Compiler\Infrastructure\CompileOptions))
#6 /usr/src/vendor/phel-lang/phel-lang/src/php/Run/Infrastructure/Command/ReplCommand.php(141): Phel\Run\Infrastructure\Command\ReplCommand->analyzeInputBuffer()
#7 /usr/src/vendor/phel-lang/phel-lang/src/php/Run/Infrastructure/Command/ReplCommand.php(98): Phel\Run\Infrastructure\Command\ReplCommand->loopReadLineAndAnalyze()
#8 /usr/src/vendor/symfony/console/Command/Command.php(279): Phel\Run\Infrastructure\Command\ReplCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /usr/src/vendor/symfony/console/Application.php(1029): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /usr/src/vendor/symfony/console/Application.php(316): Symfony\Component\Console\Application->doRunCommand(Object(Phel\Run\Infrastructure\Command\ReplCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /usr/src/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /usr/src/vendor/phel-lang/phel-lang/src/php/Console/Infrastructure/ConsoleBootstrap.php(24): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /usr/src/vendor/phel-lang/phel-lang/bin/phel(45): Phel\Console\Infrastructure\ConsoleBootstrap->run()
#14 /usr/src/vendor/phel-lang/phel-lang/bin/phel(46): {closure}()
#15 /usr/src/vendor/bin/phel(119): include('/usr/src/vendor...')
```

#### How to reproduce

Pass the vector as the second argument to the `cons` function.

#### Expected behavior

I think it would be useful to be able to equally well accept `list` and `vector` as the second argument to the `cons` function.

**Comment by Chemaclass** [comment]
Something to start looking at this issue: 
![Screenshot 2024-06-01 at 17 41 16](https://github.com/phel-lang/phel-lang/assets/5256287/f1da041b-69f9-4251-823c-48d0a6dd70b7)
Maybe adding `ConsInterface` to the `AbstractPersistentVector` would be the right way to go? 
Right now, only LinkedList is using the `ConsInterface`

**Comment by smeghead** [comment]
I think it need to added it to `PersistentVectorInterface` or `SeqInterface`.

**Comment by Chemaclass** [comment]
@smeghead wanna give a try? Feel free to open a PR with your suggestion, and we can help you from whenever you can do. Tip: start with a failing test. You can see examples in `(deftest test-cons` file: `tests/phel/test/core/basic-sequence-operation.phel:4`

**Comment by smeghead** [comment]
@Chemaclass 
I'll try to create a PR, give me a few days.
Thank you.
