### ISSUE TITLE
Improving exception output in REPL

### ISSUE THREAD

**Issue by jasalt** [phel-lang/phel-lang#765]
| Q                   | A               |
|---------------------|-----------------|
| Phel version        | 8.2.20           |
| PHP version         | v0.15.2           |

#### Summary

REPL does not show actual Throwable types (eg. `Exception` or `TypeError`) when printing uncaught exceptions, only `Phel\Compiler\Domain\Evaluator\Exceptions\CompiledCodeIsMalformedException` with only the message from original Throwable if it is given (thankfully at least). 

A long, usually non-helpful stack trace is also given.

#### Current behavior

```
user@mx-p14s ~/dev/phel-test/cli-skeleton ‹main●›
$ vendor/bin/phel repl

phel:1> (throw (php/new \TypeError))
Phel\Compiler\Domain\Evaluator\Exceptions\CompiledCodeIsMalformedException:
in /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/Domain/Evaluator/Exceptions/CompiledCodeIsMalformedException.php:14 (gen: /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/Domain/Evaluator/Exceptions/CompiledCodeIsMalformedException.php:14)

#0 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/Domain/Evaluator/RequireEvaluator.php(42): Phel\Compiler\Domain\Evaluator\Exceptions\CompiledCodeIsMalformedException::fromThrowable()
#1 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/Application/EvalCompiler.php(111): Phel\Compiler\Domain\Evaluator\RequireEvaluator->eval()
#2 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/Application/EvalCompiler.php(70): Phel\Compiler\Application\EvalCompiler->evalNode()
#3 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/CompilerFacade.php(57): Phel\Compiler\Application\EvalCompiler->evalString()
#4 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Run/RunFacade.php(79): Phel\Compiler\CompilerFacade->eval()
#5 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Run/Infrastructure/Command/ReplCommand.php(208): Phel\Run\RunFacade->eval()
#6 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Run/Infrastructure/Command/ReplCommand.php(142): Phel\Run\Infrastructure\Command\ReplCommand->analyzeInputBuffer()
#7 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Run/Infrastructure/Command/ReplCommand.php(99): Phel\Run\Infrastructure\Command\ReplCommand->loopReadLineAndAnalyze()
#8 /home/user/dev/phel-test/cli-skeleton/vendor/symfony/console/Command/Command.php(279): Phel\Run\Infrastructure\Command\ReplCommand->execute()
#9 /home/user/dev/phel-test/cli-skeleton/vendor/symfony/console/Application.php(1029): Symfony\Component\Console\Command\Command->run()
#10 /home/user/dev/phel-test/cli-skeleton/vendor/symfony/console/Application.php(316): Symfony\Component\Console\Application->doRunCommand()
#11 /home/user/dev/phel-test/cli-skeleton/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun()
#12 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Console/Infrastructure/ConsoleBootstrap.php(24): Symfony\Component\Console\Application->run()
#13 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/bin/phel(45): Phel\Console\Infrastructure\ConsoleBootstrap->run()
#14 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/bin/phel(46): {closure}()
#15 /home/user/dev/phel-test/cli-skeleton/vendor/bin/phel(120): include('/home/user/dev/...')

phel:2> (throw (php/new \TypeError "It is a TypeError BTW!"))
Phel\Compiler\Domain\Evaluator\Exceptions\CompiledCodeIsMalformedException: It is a TypeError BTW!
in /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/Domain/Evaluator/Exceptions/CompiledCodeIsMalformedException.php:14 (gen: /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/Domain/Evaluator/Exceptions/CompiledCodeIsMalformedException.php:14)

#0 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/Domain/Evaluator/RequireEvaluator.php(42): Phel\Compiler\Domain\Evaluator\Exceptions\CompiledCodeIsMalformedException::fromThrowable()
#1 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/Application/EvalCompiler.php(111): Phel\Compiler\Domain\Evaluator\RequireEvaluator->eval()
#2 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/Application/EvalCompiler.php(70): Phel\Compiler\Application\EvalCompiler->evalNode()
#3 /home/user/dev/phel-test/cli-skeleton/vendor/phel-lang/phel-lang/src/php/Compiler/CompilerFacade.php(57): Phel\Compiler\Application\EvalCompiler->evalString()
[...]
#15 /home/user/dev/phel-test/cli-skeleton/vendor/bin/phel(120): include('/home/user/dev/...')

```

#### Expected behavior
As example, [Clojure Babashka](https://github.com/babashka/babashka) (v1.12.194) REPL behavior is more convenient:
```
$ bb

user=> (throw (new AssertionError))
java.lang.AssertionError [at <repl>:1:1]

user=> (throw (new Exception "Foo is not right."))
java.lang.Exception: Foo is not right. [at <repl>:2:1]
```

- Throwable type is printed (high importance)
- Points to REPL session `<repl>`  (medium importance), 
  - code location of `throw`, counting every line written in REPL
- Long internal stack trace is hidden (lower importance)

Otherwise looking these differences, I wouldn't mind keeping the prompt number in Phel prompt as is eg. `phel:2>`.

**Comment by jasalt** [comment]
PHP shell behavior also seems somewhat more convenient, eg.

```
$ php -a

php > throw new TypeError;
PHP Warning:  Uncaught TypeError in php shell code:1
Stack trace:
#0 {main}
  thrown in php shell code on line 1

php > throw new TypeError("Foo testing!");
PHP Warning:  Uncaught TypeError: Foo testing! in php shell code:1
Stack trace:
#0 {main}
  thrown in php shell code on line 1
```

**Comment by jasalt** [comment]
Old related issue https://github.com/phel-lang/phel-lang/pull/604
